### ISSUE TITLE
Samsung Galaxy S6

### ISSUE THREAD

**Issue by incognitojam** [LeaVerou/dpi#106]
The Samsung Galaxy S6 has a resolution of 1440x2560 with a display size of 5.1", making for a dpi of approximately 577.

The S6 Edge has the same specifications.

**Comment by LeaVerou** [comment]
Thanks! Pull request? :)

**Comment by incognitojam** [comment]
I tried to make one, but I'm not sure if it worked. I'm new to Github! I'll try again.

(Sorry for the late reply!)

**Comment by alimd** [comment]
done and dppx fixed in pl #115 ;)
