### ISSUE TITLE
DPI not displaying correctly on Apple Devices (iPhone 6, iMac 27" non-Retina)

### ISSUE THREAD

**Issue by UniqueFavorsWeb** [LeaVerou/dpi#128]
I tested dpi.lv on both my iMac 27" (non-retina) and iPhone 6. The iMac (attached screenshot) is showing 221 DPI, even though the number on the list is 102. Likewise, when I view from my iPhone 6 it is only reporting 115 DPI when it should be 326.
![screen shot 2015-07-13 at 12 52 42 pm](https://cloud.githubusercontent.com/assets/13318668/8655379/bd5d1e9e-295e-11e5-8f0a-d34e62b6ccec.png)

anyway to resolve?

**Comment by fritzmg** [comment]
You highlighted the wrong iMac - that'd the 21.5" one. Also in the calculator above, you entered the wrong diagonal (13.3" instead of 27").
