### ISSUE TITLE
Virtual Reality makes this library VERY valuable

### ISSUE THREAD

**Issue by pindiespace** [LeaVerou/dpi#145]
VR devices need to know the actual size of a cellphone placed in, say, Google Cardboard or Samsung Gear VR. Current VR libraries are doing some basic sniffing, but not enough to really make a boilerplate for WebVR. The more data on large-format smartphones (e.g. 5" and 6" models) the better!

**Comment by LeaVerou** [comment]
Yay, glad to know!! I had never thought of that when making it :)
