### ISSUE TITLE
Add Tesco Hudl 2

### ISSUE THREAD

**Issue by clagnut** [LeaVerou/dpi#152]
Resolution is 1920 x 1200
dppx is 2
diagonal is 8.3"
273 dpi
user agent: Mozilla/5.0 (Linux; Android 4.4.2; Hudl 2 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Safari/537.36

**Comment by LeaVerou** [comment]
Pull request please?

**Comment by clagnut** [comment]
OK. I was just being a bit lazy/pressed for time.

**Comment by LeaVerou** [comment]
Yeah, I’m also lazy and pressed for time though. :)

**Comment by clagnut** [comment]
I don't think 'lazy' is something you could be labelled as Lea :-)

**Comment by clagnut** [comment]
Added pull request https://github.com/LeaVerou/dpi/pull/153
