### ISSUE TITLE
Issue with correctly reading a 29" 21x9 monitor.  Reads diagonal as 13.3" 

### ISSUE THREAD

**Issue by NoWay1969** [LeaVerou/dpi#170]
Reads diagonal as 13.3"  & resolution as 2814.9000610113144 x 2814.9000610113144.  Graphics cards just reads it as LG Ultrawide.

**Comment by LeaVerou** [comment]
13.3" is the default value. There is no way to detect your physical screen size.

**Comment by arkon** [comment]
This could have something to do with the fact that 21:9 screens are just two panels place side by side. I'm closing for now though.
