### ISSUE TITLE
Inaccurate dppx values?

### ISSUE THREAD

**Issue by zachleat** [LeaVerou/dpi#186]
It seems unlikely that all of these dppx values would be 1?

![image](https://cloud.githubusercontent.com/assets/39355/26632977/7f49b4f4-45d7-11e7-8dae-1493fb67ea3c.png)

Specifically, my own Google Pixel device has a dppx value of 2.63, according to https://mydevice.io/ This data lists the Google Pixel dppx value as 1 though.

Should these values be changed to _Unknown_ or something?

**Comment by arkon** [comment]
Yes, it's probably better to just show something like `?` rather than defaulting to `1`.

**Comment by LeaVerou** [comment]
Heh, back when this website was first made, defaulting to 1 made sense.

**Comment by arkon** [comment]
Made it so it just shows `?` if it's not explicitely set in #188.
