### ISSUE TITLE
Wrong diagonal screen size calculated leading to wrong dpi

### ISSUE THREAD

**Issue by Spikatrix** [LeaVerou/dpi#187]
I'm using a Lenovo A3300-HV tablet. It has a resolution of 1024x600 and a dpi of 169 (Verfied by a third-party app CPU-Z). It is a 7" tablet

Your site http://dpi.lv , on visiting from the tablet correctly displays the resolution but incorrectly calculated the diagonal screen size. It should have been 7" but the site displayed 13.3" leading to a wrong dpi (89, instead of 169).

FWIW, I used the latest version of Chrome for Android when visiting your site

**Comment by arkon** [comment]
Unfortunately, there's no way to tell how large the screen is physically from the browser, so it relies on the user inputting that value.
