### ISSUE TITLE
Galaxy S8/S8+

### ISSUE THREAD

**Issue by chuman72486** [LeaVerou/dpi#189]
Please add new device Galaxy S8 and S8+.

Samsung Galaxy S8 - 1440x2960 5.8"
Samsung Galaxy S8+ - 1440x2960 6.2"

**Comment by arkon** [comment]
PRs are welcome!

**Comment by tplive** [comment]
Added PR. :)

**Comment by LeaVerou** [comment]
Merged PR :)
