### ISSUE TITLE
Calculation is incorrect for MBP + ACD

### ISSUE THREAD

**Issue by brendanfalkowski** [LeaVerou/dpi#20]
With a 24" LED Cinema Display (1920x1200) attached to a closed 17" MPB (1920x1200), the site thinks my diagonal is 13.3in and 170 PPI. This is wrong for both screens, not sure why.

Aside, cool plane-project!

**Comment by LeaVerou** [comment]
The site doesn’t "think" anything about your diagonal, since it’s impossible to get through JS. 13.3" is just the default value :P

**Comment by brendanfalkowski** [comment]
Hmm, I assumed the site was guessing those values since it matched my resolution correctly. Might be clearer to not assign a default for values that can't be interpreted. Was just a bit confused on first landing.

**Comment by LeaVerou** [comment]
If I don’t assign a default value, there would also be no dpi result to show, and I want to illustrate how the site works at first glance.
Not sure how I can communicate that these values are meant to be edited :(

**Comment by brendanfalkowski** [comment]
Maybe start with a known quantity like iPad 3, and then indicate the values can be tweaked.

**Comment by LeaVerou** [comment]
But it does try to guess the resolution, which is pretty useful I think.

**Comment by brendanfalkowski** [comment]
Hmm, I guess it didn't block me learning how to use the site. Probably don't worry about it.
