### ISSUE TITLE
List iPhone 4 and iPhone 4S separately, same for iPhone 1, 3G, 3GS

### ISSUE THREAD

**Issue by paultreny** [LeaVerou/dpi#28]
While it is quite clear to me that "iPhone 4(S)" means "iPhone 4" and "iPhone 4S", it could be confusing to those less tech-savvy, and also doesn't show up when i type "4S", or "iPhone 4S" in the search box.

The same thing applies for the "iPhone 1 & 3G(S)"

Not meant to be nitpicky or to create extra work for you!

I may make a pull request but have to get a few other things done today first!

**Comment by mgold** [comment]
It's a matter of opinion, but mine is that the current way is clear and much more compact.

**Comment by LeaVerou** [comment]
If you want to send a pull request for that, I will merge it.

**Comment by teleject** [comment]
Made a quick change to correspond with @paultreny's issue and sent pull request.
