### ISSUE TITLE
Wrong Diagonal

### ISSUE THREAD

**Issue by mauryaratan** [LeaVerou/dpi#36]
Hey @LeaVerou, thanks for such a useful site and created while travelling? Awesome!

Anyways, when I view the site on Retina MacBook 15" it shows wrong diagonal. Instead of 15.4" it shows 13.3", thought I should let you know :smile:

**Comment by LeaVerou** [comment]
It’s just the default value. You are meant to change it. Diagonals cannot be detected by JavaScript.

**Comment by mauryaratan** [comment]
Silly me! Sorry for wasting your time!
