### ISSUE TITLE
Bad values for Nokia Lumia 1020

### ISSUE THREAD

**Issue by raphaelgoetter** [LeaVerou/dpi#65]
Hello,

dpi.lv says that my Lumia 1020 has : 
- a 13.3" diagonal
- a 53 pixels per inch resolution

Actually, the right value is 4.5″ and 332dpi

**Comment by LeaVerou** [comment]
It doesn't say anything about your diagonal because there is no way to detect that. You are looking at the default value. You are supposed to edit it.

**Comment by raphaelgoetter** [comment]
Ah OK, alright. 
However, this could be mentioned on the website since we do not expect it necessarily. 
Indeed, the resolution (on the left) is automatically computed. How could we doubt that this is not the case with the diagonal?

**Comment by LeaVerou** [comment]
If you can think of any way to indicate it, I'm open to ideas. More text on the website wouldn't be a good idea though. Most people don't read.

**Comment by raphaelgoetter** [comment]
Perhaps some kind of tooltip ?

**Comment by LeaVerou** [comment]
If the user is already mousing over there or clicking on it, chances are they're going to edit it anyway.
