### ISSUE TITLE
Add Micromax A110

### ISSUE THREAD

**Issue by MihirGosai** [LeaVerou/dpi#69]
{
- ```
    "name": "Micromax A110",
  ```
- ```
    "w": 480,
  ```
- ```
    "h": 856,
  ```
- ```
    "d": 4.9,
  ```
- ```
    "ppi": 200
  ```

}

**Comment by LeaVerou** [comment]
Thanks! Pull request?

**Comment by MihirGosai** [comment]
Yes dear :)

**Comment by LeaVerou** [comment]
I mean, could you send a pull request? https://help.github.com/articles/using-pull-requests

**Comment by febrychou** [comment]
what's file is it ?

**Comment by LeaVerou** [comment]
screens.json
