### ISSUE TITLE
incorrect diagonal when used with dual display

### ISSUE THREAD

**Issue by andykleeman** [LeaVerou/dpi#9]
Hi Lea,

Firstly, nice work and thanks for sharing.

I noticed when viewing on a 13 inch MBP plugged into an external 24inch cinema display - moving the browser window between screens and refreshing updates the resolution correctly but not the diagonal - this stays at 13.3 even when viewing on the cinema display..

Hopefully that makes sense - let me know if you'd like any further information.

Andy

**Comment by alimd** [comment]
because javascript screen object access default screen.

**Comment by LeaVerou** [comment]
Hi there,

There is currently NO way to get the sceen diagonal in inches through JavaScript, I’ve looked into this a lot in the past. The 13.3" is just a static default value, nothing more. Both these fields are editable, so you can input your specs manually of course. :)
