### ISSUE TITLE
BlackBerry Passport

### ISSUE THREAD

**Issue by andygryc** [LeaVerou/dpi#92]
1440 x 1440 pixels, 4.5 inches (~453 ppi pixel density)

**Comment by LeaVerou** [comment]
Thanks! Pull request?

**Comment by andygryc** [comment]
I’ve used Git once before, but it’s not at all intuitive to me. If “pull request” means that you’d like me to fork the repo, make some changes, then “commit” them by asking you to pull them, I’m not sure that I’d be able to do that properly. I was very much hoping to avoid all of that by just telling you the entry I was hoping you would add.

I’m pretty old school—I still use SVN :-(

—Andy

**Comment by LeaVerou** [comment]
Github has a web interface that does all this for you behind the scenes, all you need to do is click edit, make the change and enter a message IIRC :)

**Comment by andygryc** [comment]
Well you’re quite right—that was easy. Thanks!
—Andy
