### ISSUE TITLE
Is the Nexus 9 ddpx of 1 correct?

### ISSUE THREAD

**Issue by Jakobud** [LeaVerou/dpi#96]
It says it has a dppx of 1 on the live site. Can anyone confirm this for sure? I would think a 9" tablet with resolution that high would be at least a dppx of 2. The iPad's that have the same resolution have dppx of 2.

**Comment by alimd** [comment]
off course not
When dpi.lv don't know a dppx show the 1 number ! and i think its make issue for many

**Comment by Jakobud** [comment]
Ah I didn't know it defaults to 1. That is not a good idea. Should just be blank. I have tried to submit pull requests to fix some devices but I am assuming at this point that the project has been abandoned and they aren't accepting pull requests anymore. There are PRs from 2013 that still haven't been brought in. Too bad.

**Comment by alimd** [comment]
I super-agree width you, I make the mistake many time like you and fix it
as soon as possible if Ms. @leaverou has the same idea and accept pull
request
